language: php
php:
  - 5.3
  - 5.4
  - 5.6
  - 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
script:
  - redis-server tests/redis.conf
  - cd tests; phpunit
